
# -----------------------------------------------------------------------------
# GW+EDMFT
# -----------------------------------------------------------------------------
[gw_edmft]
outdir = "./"
prefix = "svo"

niter = 1               # Number of GW+EDMFT cycles
gw_iter_per_loop = 1    # Number of GW updates per outer cycle
edmft_iter_per_loop = 1 # Number of EDMFT updates per outer cycle

screen_type = "gw_edmft"  # Screening model: gw_edmft or rpa
div_treatment = "gygi_metal"      #q->0 divergence treatment

[gw_edmft.iter_alg]
alg = "damping"
mixing = 0.15

# -----------------------------------------------------------------------------
# EDMFT controls
# -----------------------------------------------------------------------------
[gw_edmft.edmft]
chkpt_h5 = "svo.dmft.h5" # Default would be: {outdir}/{prefix}.mbpt.h5

[gw_edmft.edmft.iaft]
wmax = 5              # DLR frequency cutoff for EDMFT subspaces
eps = 1e-10           # DLR target precision for EDMFT subspaces

# -----------------------------------------------------------------------------
# Impurity solver block
# Add multiple [[gw_edmft.edmft.impurity]] sections for multiple impurities.
# -----------------------------------------------------------------------------
[[gw_edmft.edmft.impurity]]
init_imp_results = "dc"           # Initial impurity self-energy/polarization: dc or zero
degenerate_blk = [[0, 1, 2, 3, 4, 5]]

n_iw = 3000
n_tau = 96001
length_cycle = 60
n_warmup_cycles = 6000
n_cycles = 2000000

measure_pert_order = true
perform_tail_fit = true
fit_max_moment = 12
fit_min_w = 1.8
fit_max_w = 4.5

# Impurity chemical potential solver
[gw_edmft.edmft.impurity.chemical_potential]
verbosity = true
tolerance = 0.1
length_cycle = 60
n_warmup_cycles = 1000
n_cycles = 100000

# Optional regularization / causality projection controls
[gw_edmft.edmft.impurity.causal_projection]
exclude_w0 = false
w0_treatment_for_pi = "extrapolate_order_2"
# w0_treatment_for_w = "flatten"
# w0_treatment_for_weiss = "flatten"
nbath_per_orbital = -1
