"""
==========================================================================
CoQuí: Correlated Quantum ínterface

Copyright (c) 2022-2026 Simons Foundation & The CoQuí developer team

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==========================================================================
"""

import json

from coqui._lib import wannier_module 

# no returns yet, decide what and how to return later

def wannier90(mf, params):
  """
  Generates MLWF, using Wannier90 in library mode. A *.win file is required with this routine. 
  This routine is equivalent to executing the following commands, with a given prefix.win file:
    wannier90.x -pp prefix
    pw2wannier90.x param_file
    wannier90.x prefix

  Parameters
  ----------
  mf : coqui Mf class
    The mean-field handler for the target system.

  params: dict
    Parameters for the Wannier90 calculation. Supported parameters are: 

      - prefix: string, required.
        Equivalent to wannier90's seedname.
        CoQuí resolves seedname as outdir + "/" + prefix.
        The file (outdir/prefix).win must exist and should contain wannier90 parameters.
        The file does not need to contain the following parameters, they are supplied by CoQui. 
        If they exist, they must be consistent with CoQui's values.
          1. atoms_cart/atoms_frac block,
          2. unit_cell_cart block.
        The kpoints block can be provided and can be different from CoQui's internal kpoint list,
        as long as they represent an equivalent list of kpoints, (e.g same list of kpoints, 
        up to lattice translation) 

      - outdir: string, default="./"
        Directory where Wannier90 input/output files are read/written.
        
      - write_mmn: bool, default=False
        If True, write overlap file, prefix.mmn.

      - write_amn: bool, default=False
        If True, write initial projections file, prefix.amn.

      - write_eig: bool, default=False
        If True, write eigenvalue file, prefix.eig.

      - write_nnkp: bool, default=False
        If True, write pre-processing file, prefix.nnkp.
        Equivalent to executing wannier90.x -pp prefix

      - write_modest: bool, default=True
        If True, write ModEST's h5 file.
        Used to interface with ModEST for quantum embedding calculations.

    Options used during ModEST h5 generation: 

      - dset_name: string, default = "dft_input".
        Name of h5 dataset.

      Shell information. Each option, if included, must be an array of the same length.
        Each element in the array corresponds to a given shell.
        If the number of shells is greater than 1, shells.dim must be provided. 

        - shells.atoms: Array, default = [0].
          Atom id of the shell.

        - shells.sort: Array, default = [0].

        - shells.l: Array, default = [0].
          Angular momentum of each shell.
           
        - shells.dim: Array, default = [num_wann].
          Number of wannier orbitals in each shell. The sum must be smaller or equal to num_wann.
          Orbitals are taken in the order generated by wannier90. No reordering of wannier
          orbitals is currently allowed.

        - shells.SO: Array, default = [0].
         
        - shells.irrep: Array, default = [0].

      - charge_below: integer, default = 0
      
      - density_required: double, default = total charge in included bands.

      - bloch_basis: bool, default = True.  (Only True currently allowed/implemented)
        If True, returns hamiltonian matrix elements in the bloch basis.
        Otherwise, returns hamiltonian matrix elements in the Wannier basis.

    (Advanced) Options for the generation of initial projections:
     
      - r0: double, default = exp(-6).
        Initial point in the radial grid used to solve the spherical bessel transform.
        The actual initial point used in the evaluation is scaled by zona, the coefficient
        in the exponent of the radial function.

      - rN: double, default = 10.0.
        Last point in the radial grid used to solve the spherical bessel transform.
        The actual last point used in the evaluation is scaled by zona, the coefficient
        in the exponent of the radial function.

      - nr: integer, default = 333.
        Number of points in the radial grid.

  Returns
  -------
  """
  wannier_module.wannier90_library_mode(mf, json.dumps(params))

def coqui2wannier90(mf, params):
  """
  Generates the overlap, initial projection and eigenvalue files for a later
  wannier90 calculation. The prefix.nnkp file is required.  
  This routine is equivalent to executing: 
    pw2wannier90.x param_file

  Parameters
  ----------
  mf : coqui Mf class
    The mean-field handler for the target system.

  params: dict
    Parameters for CoQui to Wannier90 converter. Supported parameters are: 

      - prefix: string, required.
        Equivalent to wannier90's seedname.
        CoQuí resolves seedname as outdir + "/" + prefix.
        The file (outdir/prefix).nnkp must exist, as generated by wannier90.x -pp prefix.
        The file does not need to contain the following parameters, they are supplied by CoQui. 
        If they exist, they must be consistent with CoQui's values.
          1. real_lattice 
          2. recip_lattice 
        The kpoints block can be provided and can be different from CoQui's internal kpoint list,
        as long as they represent an equivalent list of kpoints, (e.g same list of kpoints, 
        up to lattice translation) 

      - outdir: string, default="./"
        Directory where Wannier90 input/output files are read/written.
        
      - write_mmn: bool, default=True
        If True, write overlap file, prefix.mmn.

      - write_amn: bool, default=True
        If True, write initial projections file, prefix.amn.

      - write_eig: bool, default=True
        If True, write eigenvalue file, prefix.eig.

  """
  wannier_module.coqui2wannier90(mf, json.dumps(params))

def append_wannier90_win(mf, params):
  """
  Appends 1. atoms_cart, 2. unit_cell_cart and 3. kpoints blocks to a given Wannier90's win file.

  Parameters
  ----------
  mf : coqui Mf class
    The mean-field handler for the target system.

  params: dict
    Parameters for CoQui to Wannier90 converter. Supported parameters are:

    - prefix: string, required.
        Equivalent to wannier90's seedname.
        CoQuí resolves seedname as outdir + "/" + prefix.
        The file (outdir/prefix).win must exist.
        The file does not need to contain the following parameters, they are supplied by CoQui.
        If they exist, they must be consistent with CoQui's values.
          1. real_lattice
          2. recip_lattice
        The kpoints block can be provided and can be different from CoQui's internal kpoint list,
        as long as they represent an equivalent list of kpoints, (e.g same list of kpoints,
        up to lattice translation)

    - outdir: string, default="./"
      Directory where Wannier90 input/output files are read/written.

    - atoms: bool, default=True
      If True, add atom positions to win file.

    - kpts: bool, default=True
      If True, add kpoints to win file.

    - cell: bool, default=True
      If True, add cell_cart to win file.

  """
  wannier_module.wannier90_append_win(mf, json.dumps(params))

def mlwf_h5_from_wannier90_output(mf, params):
  """
  Read Wannier90 standalone mode output and convert to CoQuí HDF5 format.
  
  This function reads eigenvalues (.eig), U matrix (.u_mat), optional U_dis 
  matrix (.u_dis.mat), and Wannier function centres (.centres.xyz) files 
  generated by Wannier90 standalone calculations and converts them into 
  CoQuí's HDF5 MLWF format.

  Parameters
  ----------
  mf : coqui Mf class
    The mean-field handler for the target system.

  params : dict
    Parameters for reading Wannier90 standalone output. Supported parameters:

      - prefix: string, required.
        Wannier90 seedname (file prefix).
        CoQuí resolves seedname as outdir + "/" + prefix.

      - outdir: string, default="./"
        Directory where Wannier90 input/output files are read/written.

        The following files are expected:
          1. outdir/prefix.win (required) - Input file with num_wann, num_bands, exclude_bands
          2. outdir/prefix.eig (optional) - Eigenvalues. If missing, computed from DFT
          3. outdir/prefix_u.mat (required) - U rotation matrix
          4. outdir/prefix_u_dis.mat (optional) - U_dis disentanglement matrix (auto-detected)
          5. outdir/prefix_centres.xyz (required) - Wannier function centres

      - h5_filename: string, optional (default = outdir/prefix.mlwf.h5).
        Output HDF5 filename.

      - dset_name: string, optional (default = "dft_input").
        Dataset name within HDF5 file.

      - charge_below: integer, optional (default = 0).

      - density_required: double, optional.
        Default = total charge in included bands.

      - bloch_basis: bool, optional (default = True).
        If True, hamiltonian matrix elements in Bloch basis.
        Otherwise, in Wannier basis (currently only True is supported).

      Shell information (optional). If included, each option must be an array:

        - shells.atoms: Array, default = [0].
          Atom id of the shell.

        - shells.sort: Array, default = [0].

        - shells.l: Array, default = [0].
          Angular momentum of each shell.
           
        - shells.dim: Array, default = [num_wann].
          Number of wannier orbitals in each shell. Sum <= num_wann.

        - shells.SO: Array, default = [0].
         
        - shells.irrep: Array, default = [0].

  Returns
  -------
  None
    Writes HDF5 file directly to disk.
  """
  wannier_module.mlwf_h5_from_wannier90_output(mf, json.dumps(params))
