"""
Example: Prepare Wannier90 Inputs (amn/mmn) via CoQui (pw2wannier.x Equivalent)

This example demonstrates how to generate the Wannier90 overlap/projection
inputs using CoQui, analogous to the role of `pw2wannier90.x` in the standard
Quantum ESPRESSO → Wannier90 workflow.

In CoQui, the conversion step is performed by `coqui.coqui2wannier90`, which
uses an existing mean-field (MF) object to access the Bloch wavefunctions and
band information required to build:
  - `seedname.amn`: projection matrix A_{mn}
  - `seedname.mmn`: overlap matrix M_{mn}

Requirements:
  - A `seedname.nnkp` file generated by the Wannier90 pre-processing step is
    required.

Notes:
  - `coqui.coqui2wannier90` does not perform Wannierization. It only prepares the
    projection and overlap inputs needed by Wannier90, and is intended to be used
    with the Wannier90 *standalone* workflow.
  - help(coqui.coqui2wannier90) for a comprehensive list of parameters

See also
--------
- Append `seedname.win` with crystal metadata: 02a_append_wannier90_win.py
- Wannier90 *libray mode* through CoQui: 01_wannier_lib_mode.py
"""
from mpi4py import MPI
import coqui

qe_dir = coqui.TEST_INPUT_DIR + "qe/svo_kp222_nbnd40/out"

# mpi handler and verbosity
mpi = coqui.MpiHandler()
coqui.set_verbosity(mpi, output_level=2)

# Constructing a MF object
mf_params = {
    "prefix": "svo",
    "outdir": qe_dir,
    "nbnd": 40
}
svo_mf = coqui.make_mf(mpi, params=mf_params, mf_type="qe")

# prepare Wannier90 inputs (amn/mmn), analogous to pw2wannier90.x
w90_params = {
    "prefix": "svo",     # equivalent to wannier90's seedname
}
coqui.coqui2wannier90(mf=svo_mf, params=w90_params)
